In [123]:
import torch
import numpy as np
import scipy.stats



In [88]:
# calculates the inner product between two functions 
# Where f and g are both vectors that represent the coefients
# This is the for the aproximation where you are given points and not the function
def computerDotProduct(Fpoints,GPoints,): 
    return np.dot(Fpoints,GPoints)

def computeSumation(coefficients,m=20):
    total = 0
    for num in range(m+1):
        x = np.array([num**i for i in range(len(coefficients)-1,-1,-1)])
        result = np.dot(x, coefficients)
        total+=result
    return total

def compute_f_Hat(list_of_coef_f,u,n,y): 
    # U = [1,34,24].T()
    total = 0 
    for i in range(n+1):
        coef_f = list_of_coef_f[i]
        if ((computeSumation(coef_f) + computeSumation(u))) <= y:
            total+=1
    return float(total)/n
        
def computeDepth(coef_f, coef_g,m,j):
    total = 0 
    s = np.random.normal(0, 0.1, size=[j,m])
    for i in j:
        fhat = compute_f_Hat(coef_f[i],coef_g[i])
        total+= fhat* (1-fhat)
    return (1/j) * total


# h0 the samples are the same
# h1 the samples are not the same

# h = 12/(number of functions)*((number of functions)+1)
def KW_H_Test():
    constantLeft = 12/((n**2)+n)


    constantRight = -3*(n+1)

    degreeOfFreedom = n -1 
    chiSquare = scipy.stats.chi2.ppf(1-.05, df=degreeOfFreedom)
    if Hstat < chiSquare: 

In [126]:
t = np.random.randint(0,10,size=(10))

g1s1 = np.array([], dtype=int)
g1s2 = np.array([], dtype=int)
g1s3 = np.array([], dtype=int)

g2s1 = np.array([], dtype=int)
g2s2 = np.array([], dtype=int)
g2s3 = np.array([], dtype=int)

g3s1 = np.array([], dtype=int)
g3s2 = np.array([], dtype=int)
g3s3 = np.array([], dtype=int)

for x in t:
    i = t[x]
    
    g1s1 = np.append(g1s1,i**2 + 2*i +5)
    g1s2 = np.append(g1s2,i**2 + 3*i -3)
    g1s3 = np.append(g1s3,i**2 + 4*i +5)

    g2s1 = np.append(g2s1,i**2 + 4*i +1)
    g2s2 = np.append(g2s2,i**2 + 5*i -3)
    g2s3 = np.append(g2s3,i**2 + 2*i -1)
    
    g3s1 = np.append(g2s1,i**2 + 1*i +1)
    g3s2 = np.append(g2s2,i**2 + 2*i -2)
    g3s3 = np.append(g2s3,i**2 + 3*i -3)
    
print(t)
print(g1s1)
print(g1s2)
print(g1s3)

print(g2s1)
print(g2s2)
print(g2s3)

print(g3s1)
print(g3s2)
print(g3s3)

[6 2 5 5 4 0 2 8 0 8]
[13 40  5  5 29 53 40  5 53  5]
[ 7 37 -3 -3 25 51 37 -3 51 -3]
[17 50  5  5 37 65 50  5 65  5]
[13 46  1  1 33 61 46  1 61  1]
[11 47 -3 -3 33 63 47 -3 63 -3]
[ 7 34 -1 -1 23 47 34 -1 47 -1]
[13 46  1  1 33 61 46  1 61  1  1]
[11 47 -3 -3 33 63 47 -3 63 -3 -2]
[ 7 34 -1 -1 23 47 34 -1 47 -1 -3]
