In [2]:
import torch
import numpy as np
import scipy.stats



In [ ]:

def computeSumation(coefficients,m=20): # currently not used
    total = 0
    for num in range(0,m+1):
        x = np.array([num**i for i in range(len(coefficients)-1,-1,-1)])
        result = np.dot(x, coefficients)
        total+=result
    return total

In [5]:

# Takes in a n by 1 vector 
def compute_f_Hat(y,z): 
    # U = [1,34,24].T()
    total = 0 
    # Effiency note? Check if this is faster? 
    # Instead of a for loop we can multiply the vector by the inverse of y and floor the vector and then compute the sum of the vector.
    # It might be more operations but the operations it self may be faster 
    for i in range(y.shape[0]):
        if (y[i]<=z):  # 
            total+=1
    return float(total)/y.shape[0]


# X represents a singular function in points on a grid 1 x M ( where M represents the number of points n the grid)
# Xn represents the matrix for all functions   N x M (Where N is the number of functions)
# U represents the matrix of random numbers pulled from the normal distrubution with shape J x M Where J represents the unit vectors and M represents the number of points
# Note that in the example provided that there was 100 functions with 10 data points representing each function 

# This function will return the depth of function x in respect to all other functions in the data set
def depth(x, xn, u):
    depth=0
    for j in range(0,u.shape[0]):
        x_u_dot = np.dot(u[j],x)  
        xn_uj = np.matmul(xn,u[j].T) # results in a matrix that is Where xn = N x M and u[j].T = M x 1 
        # Now for each row in the xn_uj we want to see how many of those rows are less than x_u_dot 
        # Naive approach
        depth_j = compute_f_Hat(xn_uj,x_u_dot)
        depth += depth_j / u.shape[0]
    return depth

In [16]:
# calculates the inner product between two functions 
# Where f and g are both vectors that represent the coefients
# This is the for the aproximation where you are given points and not the function



def KW_H_Test(functionalDataSet: np.ndarray, UnitVectorMatrix: np.ndarray, 
              groups:np.ndarray): 
    # Takes in Xn and the group labels and pass it U 
    # Lets just assume for now that the groups are distr
    # Groups will be a 1xn array with each element refering to a row in a matrix representing its group 
    # 

    np.apply_along_axis(depth,axis=0,arr = functionalDataSet,u = UnitVectorMatrix,)
    # for i in range(0,functionalDataSet.shape[0]):
    #     print(depth(functionalDataSet[i],functionalDataSet,UnitVectorMatrix))



    # sampleList = []
    # for i in range(0,30):
    #     sampleList.append((depth(Xn[i],Xn,U),"Group1"))
    # for i in range(30,60):
    #     sampleList.append((depth(Xn[i],Xn,U),"Group2"))
    # for i in range(60,100):
    #     sampleList.append((depth(Xn[i],Xn,U),"Group3"))
    # sampleList.sort() # this does not deal with duplicate ranks so this will need to manually implemented 
    # group1Total = 0 
    # group2Total = 0 
    # group3Total = 0 
    # for tup in sampleList:
    #     if tup[1] == "Group1":
    #         group1Total += i 
    #     elif tup[1] == "Group2":
    #         group2Total += i
    #     else:
    #         group3Total += i 

    # summation = ( ((group1Total**2)/3) + ((group2Total**2)/3) + ((group3Total**2)/4))
    # hStat = 12/(10*11) * summation - 3*(10+1)
    # degreeOfFreedom = 3 -1 
    # chiSquare = scipy.stats.chi2.ppf(1-.05, df=degreeOfFreedom)

    # return(hStat>chiSquare)
        


In [17]:
Xn = np.random.random((100, 10)) # represents all the data 
U = np.random.random((20, 10))
groups = np.random.randint(1, 11, size=100) # where size must be the amount of rows in Xn 

KW_H_Test(Xn,U,groups)

TypeError: _apply_along_axis_dispatcher() missing 1 required positional argument: 'arr'

In [1]:
# print(data.shape)
# print(data["MCO"])

In [46]:
import skfda
data = skfda.datasets.fetch_cran("MCO", "fda.usc")


In [11]:
matrix1 = np.random.random((100, 10))

# Create a 10x20 matrix
matrix2 = np.random.random((10, 20))

# Perform matrix multiplication
result = np.matmul(matrix1, matrix2)
print(result.shape[1])

20


In [126]:
t = np.random.randint(0,10,size=(10))

g1s1 = np.array([], dtype=int)
g1s2 = np.array([], dtype=int)
g1s3 = np.array([], dtype=int)

g2s1 = np.array([], dtype=int)
g2s2 = np.array([], dtype=int)
g2s3 = np.array([], dtype=int)

g3s1 = np.array([], dtype=int)
g3s2 = np.array([], dtype=int)
g3s3 = np.array([], dtype=int)

for x in t:
    i = t[x]
    
    g1s1 = np.append(g1s1,i**2 + 2*i +5)
    g1s2 = np.append(g1s2,i**2 + 3*i -3)
    g1s3 = np.append(g1s3,i**2 + 4*i +5)

    g2s1 = np.append(g2s1,i**2 + 4*i +1)
    g2s2 = np.append(g2s2,i**2 + 5*i -3)
    g2s3 = np.append(g2s3,i**2 + 2*i -1)
    
    g3s1 = np.append(g2s1,i**2 + 1*i +1)
    g3s2 = np.append(g2s2,i**2 + 2*i -2)
    g3s3 = np.append(g2s3,i**2 + 3*i -3)
    
print(t)
print(g1s1)
print(g1s2)
print(g1s3)

print(g2s1)
print(g2s2)
print(g2s3)

print(g3s1)
print(g3s2)
print(g3s3)

[6 2 5 5 4 0 2 8 0 8]
[13 40  5  5 29 53 40  5 53  5]
[ 7 37 -3 -3 25 51 37 -3 51 -3]
[17 50  5  5 37 65 50  5 65  5]
[13 46  1  1 33 61 46  1 61  1]
[11 47 -3 -3 33 63 47 -3 63 -3]
[ 7 34 -1 -1 23 47 34 -1 47 -1]
[13 46  1  1 33 61 46  1 61  1  1]
[11 47 -3 -3 33 63 47 -3 63 -3 -2]
[ 7 34 -1 -1 23 47 34 -1 47 -1 -3]
